/******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/
 

var myApp = require('./myApp');
var express = require('express');
var app = express();


var port = process.env.PORT || 3000;
console.log(port)

/******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

